/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:acfdfe21-bac5-4d21-bee1-bc5fe8ec13f3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dObmQHt96",
    "aws_user_pools_web_client_id": "33a41o732bqii0v7frsvaojrng",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "orcacloud29cc11c6dcf14d1a996fbf06444a7d7f132445-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
