/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6e8ed2f3-b58c-40f3-a51e-d46fa2b613e4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MMOunnujD",
    "aws_user_pools_web_client_id": "5l3d6824qlftdf6k8a66ur2qba",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "project-orca223559-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
